#!/usr/bin/env python3

'''
This is a ROS node that subscribes to a topic. This is executed by the launch files.
The launch files search for the script name via the type field in the nodes.

roslaunch hw1 prime_number.launch
    ├── executes prime_number
    │      └── rospy.init_node("prime_number")
    └── executes prime_number_subscriber
           └── rospy.init_node("prime_number_subscriber")
'''

import rospy
from prime_number_subscriber import PrimeNumberSubscriber


if __name__ == "__main__":
    rospy.init_node("prime_number_subscriber")
    subscriber = PrimeNumberSubscriber()
    rospy.spin()
